@base_url=http://localhost:8080

POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc5NTA0OTQsInVzZXJuYW1lIjoiVGVzdCBVc2VyQSJ9.nHUKUuY5q9cNMNO8T9J6fwL1Na_JD2q35D0QJ7M2Wl4
TransactionID: "random_id"

{
  "text":"1gaa"
}