@base_url=http://localhost:8080

POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc4NzQwNTcsInVzZXJuYW1lIjoiVGVzdCBVc2VyQSJ9.m5JBNHtcVVsSJjRvuMyravi9ifr8Bh1EN0YuTZxp7WI

{
  "text":"sleep"
}